### PR TITLE
Replace all instances of 'shaur' to 'sahur' as it should be

### PR DESCRIPTION
**Pull request by 5nyper**
‏السلام عليكم ورحمة الله وبركاته

First I'd like to thank all who have put in their sincere effort in this project, May Allah reward you all and keep you steadfast!

I've been utilizing this API for a side project of mine that provides a convenient way for Muslims to be blessed with a narration of the Prophet ‎ﷺ (https://github.com/5ynatra/daily-hadith) 

I noticed there was a typo with the word `Sahur` (written as `Shaur`) so here is a PR to fix all of it's occurrences

BarakAllahufeekum!

### CODE REVIEW

**Comment by fawazahmed0** [comment]
Salam, Please see [this](https://github.com/fawazahmed0/hadith-api/issues/34#issuecomment-1364523496) and create a new PR

**Comment by fawazahmed0** [comment]
I have updated the text, it will take 1-2 days to reflect the new changes in api

**Comment by fawazahmed0** [comment]
Jazakallah for your application, may Allah bless you

**Comment by 5nyper** [comment]
Ameen, wa iyyak

**Pull request closed without merging**
