### PR TITLE
Added Arabic Book Names

### PR DESCRIPTION
**Pull request by GibreelAbdullah**
Info.json - Added arabic chapter names.

infofixer.js - StructuredClone function doesn't exist before node 17. Added a workaround

- - -
This change is [Reviewable](https://reviewable.io/reviews/fawazahmed0/hadith-api/22)

### CODE REVIEW

**Comment by fawazahmed0** [comment]
Thanks, this will breaking changes for people who have already implemented this API, I will have to look for a better way to do this.

**Comment by GibreelAbdullah** [comment]
Yeah, makes sense, let me know if you finalize the design. I can tweak this implementation.

**Comment by unkn4wn** [comment]
> Thanks, this will breaking changes for people who have already implemented this API, I will have to look for a better way to do this.

Maybe instead of changing "info.json", changing the individual Arabic json files in https://github.com/fawazahmed0/hadith-api/tree/1/editions is a better option. So its also possible to add Turkish section names in Turkish json files, Urdu section names in Urdu json files etc...

**Comment by GibreelAbdullah** [comment]
Or a v2 of api can be made

**Pull request closed without merging**
