### PR TITLE
Added Musnad Ahmad Arabic

### PR DESCRIPTION
**Pull request by GibreelAbdullah**

### CODE REVIEW

**Comment by fawazahmed0** [comment]
jsdelivr has file size limit of 20mb, I will have to see what to do.

**Comment by GibreelAbdullah** [comment]
Is there a way to check if anyone is using jsdeliver to fetch info.json?
I believe all the useful data is available in editions/

Anyway how about making a separate info.json for each collection, as I am planning on adding more books the size is going to increase further.

**Comment by fawazahmed0** [comment]
> Is there a way to check if anyone is using jsdeliver to fetch info.json?

A lot many people are using [jsdelivr](https://www.jsdelivr.com/package/gh/fawazahmed0/hadith-api)

> Anyway how about making a separate info.json for each collection, as I am planning on adding more books the size is going to increase further

Yes, Inshallah.

After [this feature](https://github.com/fawazahmed0/hadith-api/issues/77) is finished, I will merge your PR.
Note: I will work on [this](https://github.com/fawazahmed0/hadith-api/issues/77) in ramadan.

Meanwhile, you can open additional PR's for other books, I will merge them.

**Comment by GibreelAbdullah** [comment]
Closed this PR as I had to pull your latest changes and had to discard mine.
The files (database, info and editions) in my repo do have Munad Imam Ahmad, you can take it whenever you are ready.

**Pull request closed without merging**
