### PR TITLE
Fixed Tirmidhi and Formatted Decimal Numbers

### PR DESCRIPTION
**Pull request by unkn4wn**
1. I fixed the structure and translation of Tirmidhi. This should not break anything, as with the previous requests.

2. I formatted all decimal numbers in linebyline and info.json. I carefully changed all instances of ".2" to ".02" and ".3" to ".03" and so on. However, I'm not sure if this will cause any issues during updating, although I don't think it will.

### CODE REVIEW

**Comment by fawazahmed0** [comment]
Jazakallah, I find 1 issue in this PR

1. You only need to change `number.1` to `number.01` format, when the number of hadiths are 10 or more(i.e in rare cases). For example in [this case](https://github.com/fawazahmed0/hadith-api/issues/48#issuecomment-1436134988). For all other cases this isn't required (i.e same consistency needs to be maintained of `number.1` format for all other cases)

Other than that, everything is good

**Comment by unkn4wn** [comment]
What do you mean? 
Do you mean it should always be number.1/number.2/number.3 ... format except there are 10 or more ahadith, then it should be number.01/number.02/number.03 ... format ?

If yes wouldn't this be even more confusing if ".2" sometimes refers to the second hadith and sometimes refers to the twentieth hadith ?

**Comment by fawazahmed0** [comment]
> Do you mean it should always be number.1/number.2/number.3 ... format except there are 10 or more ahadith, then it should be number.01/number.02/number.03 ... format ?
yes

> If yes wouldn't this be even more confusing if ".2" sometimes refers to the second hadith and sometimes refers to the twentieth hadith ?
I agree, that this might be confusing, but the cases of 10 or more hadiths under same number are very rare

**Comment by unkn4wn** [comment]
I reverted my commit and changed only the one which has 10 or more ahadith in Tirmidhi

**Comment by fawazahmed0** [comment]
Jazakallah

**Pull request merged**
